[project]
name = "pycmcf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    #    "f3d",
    #    "ipykernel",
    "itk",
    #    "jupytext",
    "libigl",
    #    "notebook",
    "numpy",
    #    "pyvista",
    "ruff>=0.15.10",
    "scipy",
    "scipy-stubs~=1.17.0",
    #    "torch",
    "tqdm",
    "vtk",
    #    "wand",
]
