[project]
name = "pycmcf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "itk~=5.4",
    "libigl~=2.6",
    "numpy~=2.5",
    "scikit-sparse~=0.5.0",
    "scipy~=1.17",
    "vtk~=9.6",
    "deformetrica~=4.3",
]

[tool.uv.sources]
deformetrica = { workspace = true }

[tool.uv.workspace]
members = ["ext/*"]

[dependency-groups]
dev = [
    "ruff",
    "scipy-stubs",
]
