[project]
name = "deformetrica"
description = "Software for the statistical analysis of 2D and 3D shape data."
readme = "README.md"
authors = [
    { name = "ARAMIS Lab" },
    { name = "David Allemang", email = "allemang@cs.unc.edu" }
]
license-files = ["LICENSE.txt"]
dynamic = ["version"]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "nibabel>=5.4.2",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "psutil>=7.2.2",
    "pykeops>=2.3",
    "scikit-learn>=1.9.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "vtk>=9.6.1",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: X11 Applications :: Qt",
    "Operating System :: OS Independent",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries"
]

[project.scripts]
deformetrica = "deformetrica.__main__:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "deformetrica.__version__" }